# Site settings
title: spaceBase
email: spacebase@space150.com
description: > # this means to ignore newlines until "baseurl:"
  spaceBase is a boilerplate layer that can be built upon and tailored for your
  needs. It combines best practices for today’s responsive web with the core
  components we use on every project. Consider it the launch pad for your
  adventures into cyberspace.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://spacebase.space150.com" # the base hostname & protocol for your site
twitter_username: space150
github_username:  space150

# Build settings
markdown: kramdown
